import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "./components/Navbar";
// import Header from "./components/Header";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'], // You can add more weights as needed
  variable: '--font-inter', // optional for CSS variable usage
});

export const metadata: Metadata = {
  title: "HEI NOC Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${inter.variable} antialiased`}>
        {children}
        <Toaster position="top-center" richColors duration={1000}/>
      </body>
    </html>
  );
}
